"""empty message

Revision ID: 133910cf46ab
Revises: 
Create Date: 2021-07-12 13:28:28.560439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133910cf46ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('last_name', sa.String(length=511), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=511), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=511), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profiles')
    # ### end Alembic commands ###
